CREATE TABLE COUNTRIES 
(
  COUNTRY_NAME VARCHAR2(45) NOT NULL 
, COUNTRY_ID_PK NUMBER(10) GENERATED ALWAYS AS IDENTITY INCREMENT BY 1 START WITH 1 MAXVALUE 999999999 MINVALUE 1 NOT NULL 
, CONSTRAINT COUNTRIES_PK PRIMARY KEY 
  (
    COUNTRY_ID_PK 
  )
  ENABLE 
);




CREATE TABLE LOCATIONS 
(
  LOCATION_ID_PK NUMBER GENERATED ALWAYS AS IDENTITY INCREMENT BY 1 START WITH 1 MAXVALUE 999999999 MINVALUE 1 NOT NULL 
, LOCATION_ADRESS VARCHAR2(45) NOT NULL 
, LOCATION_CITY VARCHAR2(45) NOT NULL 
, LOCATION_POST_CODE VARCHAR2(20) 
, LOCATION_PHONE VARCHAR2(45) NOT NULL 
, LOCATIONS_COUNTRY_ID_FK NUMBER(10) NOT NULL 
, CONSTRAINT LOCATION_ID_PK PRIMARY KEY 
  (
    LOCATION_ID_PK 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX TABLE1_PK ON LOCATIONS (LOCATION_ID_PK ASC) 
  )
  ENABLE 
);

ALTER TABLE LOCATIONS
ADD CONSTRAINT LOCATIONS_COUNTRY_ID_FK FOREIGN KEY
(
  LOCATIONS_COUNTRY_ID_FK 
)
REFERENCES COUNTRIES
(
  COUNTRY_ID_PK 
)
ENABLE;


CREATE TABLE APARTMENTS 
(
  APARTMENT_ID_PK NUMBER(10) GENERATED ALWAYS AS IDENTITY INCREMENT BY 1 START WITH 1 MAXVALUE 999999999 MINVALUE 1 NOT NULL 
, APARTMENT_NAME VARCHAR2(45) NOT NULL 
, APARTMENT_SLEEPING_PLACES NUMBER(10) NOT NULL 
, APARTMENT_PRICE_PER_NIGTH NUMBER(10) NOT NULL 
, APARTMENT_IMAGE BLOB 
, APARTMENT_IS_BOOKED NUMBER(1) DEFAULT 0 NOT NULL 
, CONSTRAINT APARTMENTS_PK PRIMARY KEY 
  (
    APARTMENT_ID_PK 
  )
  ENABLE 
);

ALTER TABLE APARTMENTS
ADD CONSTRAINT APARTMENTS_FK1 FOREIGN KEY
(
  APARTMENT_ID_PK 
)
REFERENCES LOCATIONS
(
  LOCATION_ID_PK 
)
ENABLE;





