
CREATE TABLE USERS 
(
  USER_ID_PK NUMBER(10, 0) GENERATED ALWAYS AS IDENTITY INCREMENT BY 1 MAXVALUE 999999999 MINVALUE 1 NOCACHE NOT NULL 
, USER_FIR_NAME VARCHAR2(35 BYTE) NOT NULL 
, USER_LAST_NAME VARCHAR2(35 BYTE) NOT NULL 
, USER_PASSWORD VARCHAR2(50 BYTE) NOT NULL 
, USER_EMAIL VARCHAR2(20 BYTE) NOT NULL 
, USER_BIRTHDAY DATE NOT NULL 
, CONSTRAINT USERS_PK PRIMARY KEY 
  (
    USER_ID_PK 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX USERS_PK ON USERS (USER_ID_PK ASC) 
      LOGGING 
      TABLESPACE USERS 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;



CREATE TABLE COUNTRIES 
(
  COUNTRY_ID VARCHAR2(5 BYTE) NOT NULL 
, COUNTRY_NAME VARCHAR2(30 BYTE) NOT NULL 
, CONSTRAINT COUNTRIES_PK PRIMARY KEY 
  (
    COUNTRY_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX COUNTRIES_PK ON COUNTRIES (COUNTRY_ID ASC) 
      LOGGING 
      TABLESPACE USERS 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;


CREATE TABLE LOCATIONS 
(
  LOCATION_ID_PK NUMBER(10, 0) GENERATED ALWAYS AS IDENTITY INCREMENT BY 1 MAXVALUE 999999999 MINVALUE 1 NOCACHE NOT NULL 
, LOCATION_ADRESS VARCHAR2(50 BYTE) NOT NULL 
, LOCATION_CITY VARCHAR2(20 BYTE) NOT NULL 
, LOCATION_POST_CODE VARCHAR2(10 BYTE) NOT NULL 
, LOCATIONS_COUNTRY_ID_FK VARCHAR2(5 BYTE) NOT NULL 
, CONSTRAINT LOCATIONS_PK PRIMARY KEY 
  (
    LOCATION_ID_PK 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX LOCATIONS_PK ON LOCATIONS (LOCATION_ID_PK ASC) 
      LOGGING 
      TABLESPACE USERS 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;

ALTER TABLE LOCATIONS
ADD CONSTRAINT LOCATIONS_COUNTRY_ID_FK FOREIGN KEY
(
  LOCATIONS_COUNTRY_ID_FK 
)
REFERENCES COUNTRIES
(
  COUNTRY_ID 
)
ENABLE;



CREATE TABLE APARTMENTS 
(
  APARTMENT_ID_PK NUMBER(10, 0) GENERATED ALWAYS AS IDENTITY INCREMENT BY 1 MAXVALUE 999999999 MINVALUE 1 NOCACHE ORDER NOT NULL 
, APARTMENT_NAME VARCHAR2(40 BYTE) NOT NULL 
, APARTMENT_SLEEPING_PLACES NUMBER(2, 0) NOT NULL 
, APARTMENT_PRICE_PER_NIGTH NUMBER(10, 0) NOT NULL 
, APARTMENT_LOCATION_ID NUMBER(10, 0) NOT NULL 
, CONSTRAINT APARTMENTS_PK PRIMARY KEY 
  (
    APARTMENT_ID_PK 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX APARTMENTS_PK ON APARTMENTS (APARTMENT_ID_PK ASC) 
      LOGGING 
      TABLESPACE USERS 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;

ALTER TABLE APARTMENTS
ADD CONSTRAINT APARTMENTS_LOCATION_FK FOREIGN KEY
(
  APARTMENT_LOCATION_ID 
)
REFERENCES LOCATIONS
(
  LOCATION_ID_PK 
)
ENABLE;











CREATE TABLE REQUEST 
(
  REQUEST_ID NUMBER(10, 0) GENERATED ALWAYS AS IDENTITY INCREMENT BY 1 MAXVALUE 999999999 MINVALUE 1 NOCACHE NOT NULL 
, REQUEST_START_DATE DATE NOT NULL 
, REQUEST_END_DATE DATE NOT NULL 
, REQUEST_APARTMENT_ID_FK NUMBER(10, 0) NOT NULL 
, REQUEST_USER_ID_FK NUMBER(10, 0) NOT NULL 
, CONSTRAINT REQUEST_PK PRIMARY KEY 
  (
    REQUEST_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX REQUEST_PK ON REQUEST (REQUEST_ID ASC) 
      LOGGING 
      TABLESPACE USERS 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;

ALTER TABLE REQUEST
ADD CONSTRAINT REQUEST_APARTMENT_FK FOREIGN KEY
(
  REQUEST_APARTMENT_ID_FK 
)
REFERENCES APARTMENTS
(
  APARTMENT_ID_PK 
)
ENABLE;

ALTER TABLE REQUEST
ADD CONSTRAINT REQUEST_USER_FK FOREIGN KEY
(
  REQUEST_USER_ID_FK 
)
REFERENCES USERS
(
  USER_ID_PK 
)
ENABLE;

