INSERT INTO COUNTRIES (COUNTRY_NAME) VALUES ('Argentina');
INSERT INTO COUNTRIES (COUNTRY_NAME) VALUES ('Australia');
INSERT INTO COUNTRIES (COUNTRY_NAME) VALUES ('Belgium');
INSERT INTO COUNTRIES (COUNTRY_NAME) VALUES ('Brazil');
INSERT INTO COUNTRIES (COUNTRY_NAME) VALUES ('Canada');
INSERT INTO COUNTRIES (COUNTRY_NAME) VALUES ('Switzerland');
INSERT INTO COUNTRIES (COUNTRY_NAME) VALUES ('China');
INSERT INTO COUNTRIES (COUNTRY_NAME) VALUES ('Germany');
INSERT INTO COUNTRIES (COUNTRY_NAME) VALUES ('Denmark');
INSERT INTO COUNTRIES (COUNTRY_NAME) VALUES ('Egypt');
INSERT INTO COUNTRIES (COUNTRY_NAME) VALUES ('France');
INSERT INTO COUNTRIES (COUNTRY_NAME) VALUES ('Israel');
INSERT INTO COUNTRIES (COUNTRY_NAME) VALUES ('India');
INSERT INTO COUNTRIES (COUNTRY_NAME) VALUES ('Italy');
INSERT INTO COUNTRIES (COUNTRY_NAME) VALUES ('Japan');
INSERT INTO COUNTRIES (COUNTRY_NAME) VALUES ('Kuwait');
INSERT INTO COUNTRIES (COUNTRY_NAME) VALUES ('Malaysia');
INSERT INTO COUNTRIES (COUNTRY_NAME) VALUES ('Mexico');
INSERT INTO COUNTRIES (COUNTRY_NAME) VALUES ('Nigeria');
INSERT INTO COUNTRIES (COUNTRY_NAME) VALUES ('Netherlands');
INSERT INTO COUNTRIES (COUNTRY_NAME) VALUES ('Singapore');
INSERT INTO COUNTRIES (COUNTRY_NAME) VALUES ('United Kingdom');
INSERT INTO COUNTRIES (COUNTRY_NAME) VALUES ('United States of America');
INSERT INTO COUNTRIES (COUNTRY_NAME) VALUES ('Zambia');
INSERT INTO COUNTRIES (COUNTRY_NAME) VALUES ('Zimbabwe');



